"""
CreateMyWay material generator.

Automatically generates:
- Display names for custom gems and handles.
- Starter acquisition recipes for custom gems and handles.

Place this file directly inside kubejs/ and run:
    py create_my_way_material_generator.py

Only modifies:
    assets/createmyway/lang/en_us.json
    server_scripts/generated_cmw_material_recipes.js
"""

from pathlib import Path
import json


ROOT = Path(__file__).resolve().parent

MATERIALS = ROOT / "data/createmyway/slag/materials"
LANG = ROOT / "assets/createmyway/lang/en_us.json"
RECIPES = ROOT / "server_scripts/generated_cmw_material_recipes.js"


# Convert S&E fluids to Create: Metallurgy fluids when necessary.
FLUID_ALIASES = {
    "slag:molten_iron": "createmetallurgy:molten_iron",
}


def js_string(value):
    return json.dumps(value, ensure_ascii=False)


def acquisition_input(material, file):
    repair = material.get("repair_ingredient", {})

    if "tag" in repair:
        return "#" + repair["tag"]

    if "item" in repair:
        return repair["item"]

    raise ValueError(
        f"{file.name}: Missing repair_ingredient.tag or .item"
    )


def get_profile(material_id):
    """
    Determine which custom part this material belongs to.

    Examples:
        createmyway:iron_handle -> handle
        createmyway:amethyst_gem -> gem
    """

    namespace, separator, name = material_id.partition(":")

    if separator != ":" or namespace != "createmyway":
        return None

    if name.endswith("_handle"):
        return name, "handle"

    if name.endswith("_gem"):
        return name, "gem"

    return None


def display_name(name, part):
    base = name[: -(len(part) + 1)]

    return (
        " ".join(word.capitalize() for word in base.split("_"))
        + " "
        + part.capitalize()
    )


def generate_handle_recipe(material, material_id, name):
    fluid = material.get("molten_fluid")

    if not fluid:
        raise ValueError(
            f"{material_id}: Handle requires molten_fluid"
        )

    fluid = FLUID_ALIASES.get(fluid, fluid)

    item = (
        "slag:dynamic_part["
        f'slag:material_type="{material_id}",'
        'slag:part_type="createmyway:handle"]'
    )

    recipe_id = f"createmyway:form_{name}"

    return [
        "  event.recipes.createmetallurgy.casting_in_table(",
        f"    Item.of({js_string(item)}),",
        "    [",
        f"      Fluid.of({js_string(fluid)}, 45),",
        '      "createmetallurgy:graphite_rod_mold"',
        "    ]",
        f"  ).processingTime(30).id({js_string(recipe_id)})",
        "",
    ]


def generate_gem_recipe(material, material_id, name, file):
    ingredient = acquisition_input(material, file)

    item = (
        "slag:dynamic_part["
        f'slag:material_type="{material_id}",'
        'slag:part_type="createmyway:gem"]'
    )

    recipe_id = f"createmyway:form_{name}"

    return [
        "  event.recipes.create.cutting(",
        f"    Item.of({js_string(item)}),",
        f"    Ingredient.of({js_string(ingredient)})",
        f"  ).id({js_string(recipe_id)})",
        "",
    ]


def main():
    if not MATERIALS.is_dir():
        raise SystemExit(
            f"Could not find material folder: {MATERIALS}"
        )

    # Preserve existing translations.
    if LANG.exists():
        translations = json.loads(
            LANG.read_text(encoding="utf-8-sig")
        )
    else:
        translations = {}

    if not isinstance(translations, dict):
        raise ValueError("en_us.json must contain a JSON object")

    recipes = [
        "// AUTO-GENERATED BY create_my_way_material_generator.py",
        "// Do not edit this file manually.",
        "",
        "ServerEvents.recipes(event => {",
        "",
    ]

    name_count = 0
    recipe_count = 0

    seen_ids = set()

    # Discover all material JSON files automatically.
    for file in sorted(MATERIALS.glob("*.json")):

        material = json.loads(
            file.read_text(encoding="utf-8-sig")
        )

        material_id = material["id"]
        profile = get_profile(material_id)

        # Ignore unrelated material definitions.
        if profile is None:
            continue

        name, part = profile

        if material_id in seen_ids:
            raise ValueError(
                f"Duplicate material ID: {material_id}"
            )

        seen_ids.add(material_id)

        # -----------------------------------------
        # AUTOMATIC DISPLAY NAME
        # -----------------------------------------

        translation_key = (
            f"item.createmyway.{name}_{part}"
        )

        translations[translation_key] = display_name(
            name, part
        )

        name_count += 1

        # -----------------------------------------
        # OPTIONAL RECIPE GENERATION
        # -----------------------------------------

        # Special progression materials can disable
        # their starter recipe in their JSON file:
        #
        # "generate_acquisition_recipe": false

        if not material.get(
            "generate_acquisition_recipe", True
        ):
            continue

        if part == "handle":
            recipes.extend(
                generate_handle_recipe(
                    material,
                    material_id,
                    name
                )
            )

        elif part == "gem":
            recipes.extend(
                generate_gem_recipe(
                    material,
                    material_id,
                    name,
                    file
                )
            )

        recipe_count += 1

    recipes.append("})")

    # -----------------------------------------
    # WRITE OUTPUT FILES
    # -----------------------------------------

    LANG.parent.mkdir(parents=True, exist_ok=True)
    RECIPES.parent.mkdir(parents=True, exist_ok=True)

    LANG.write_text(
        json.dumps(
            translations,
            ensure_ascii=False,
            indent=2
        ) + "\n",
        encoding="utf-8"
    )

    RECIPES.write_text(
        "\n".join(recipes) + "\n",
        encoding="utf-8"
    )

    print()
    print("CreateMyWay generation complete!")
    print(f"Generated names:   {name_count}")
    print(f"Generated recipes: {recipe_count}")
    print(f"Language file:     {LANG}")
    print(f"Recipe file:       {RECIPES}")
    print()


if __name__ == "__main__":
    main()