// Add reach modifiers at the same native item-attribute hook Better Combat reads.
// This preserves every modifier generated by Slag & Embers and adds only the gem bonus.
(function () {
  const ItemAttributeModifierEvent = Java.loadClass('net.neoforged.neoforge.event.ItemAttributeModifierEvent')
  const Attributes = Java.loadClass('net.minecraft.world.entity.ai.attributes.Attributes')
  const AttributeModifier = Java.loadClass('net.minecraft.world.entity.ai.attributes.AttributeModifier')
  const EquipmentSlotGroup = Java.loadClass('net.minecraft.world.entity.EquipmentSlotGroup')
  const ResourceLocation = Java.loadClass('net.minecraft.resources.ResourceLocation')

  function effectFor(stack) {
    if (!stack || stack.empty || stack.id !== 'slag:modular_item') return null
    const equipment = String(stack.get('slag:modular_type')).replace(/^slag:/, '')
    const parts = stack.get('slag:dynamic_parts')
    const registry = global.cmwEquipmentRegistry
    if (!parts || !registry) return null

    for (const part of parts.items()) {
      if (String(part.get('slag:part_type')) === 'createmyway:gem') {
        const gem = String(part.get('slag:material_type'))
        return ((registry.materialEffects[gem] || {})[equipment] || null)
      }
    }
    return null
  }

  NativeEvents.onEvent(ItemAttributeModifierEvent, event => {
    const effect = effectFor(event.itemStack)
    if (!effect) return

    if (effect.block_reach) {
      event.addModifier(
        Attributes.BLOCK_INTERACTION_RANGE,
        new AttributeModifier(
          ResourceLocation.fromNamespaceAndPath('createmyway', 'gem_block_reach'),
          effect.block_reach,
          AttributeModifier.Operation.ADD_VALUE
        ),
        EquipmentSlotGroup.MAINHAND
      )
    }

    if (effect.attack_reach) {
      event.addModifier(
        Attributes.ENTITY_INTERACTION_RANGE,
        new AttributeModifier(
          ResourceLocation.fromNamespaceAndPath('createmyway', 'gem_attack_reach'),
          effect.attack_reach,
          AttributeModifier.Operation.ADD_VALUE
        ),
        EquipmentSlotGroup.MAINHAND
      )
    }
  })
})()
