// AUTO-GENERATED BY create_my_way_material_generator.py
// Do not edit this file manually.

global.cmwEquipmentRegistry = {
  "materialParts": {
    "createmyway:amethyst_gem": "createmyway:gem",
    "createmyway:copper_handle": "createmyway:handle",
    "createmyway:cut_diamond_gem": "createmyway:gem",
    "createmyway:cut_dulling_gem": "createmyway:gem",
    "createmyway:cut_ember_gem": "createmyway:gem",
    "createmyway:cut_emerald_gem": "createmyway:gem",
    "createmyway:cut_frost_gem": "createmyway:gem",
    "createmyway:cut_lapis_gem": "createmyway:gem",
    "createmyway:cut_quartz_gem": "createmyway:gem",
    "createmyway:cut_rose_quartz_gem": "createmyway:gem",
    "createmyway:cut_venom_gem": "createmyway:gem",
    "createmyway:cut_wither_gem": "createmyway:gem",
    "createmyway:deep_alloy_handle": "createmyway:handle",
    "createmyway:diamond_handle": "createmyway:handle",
    "createmyway:echo_gem": "createmyway:gem",
    "createmyway:gold_handle": "createmyway:handle",
    "createmyway:iron_handle": "createmyway:handle",
    "createmyway:netherite_handle": "createmyway:handle",
    "createmyway:obsidian_handle": "createmyway:handle",
    "createmyway:perfect_amethyst_gem": "createmyway:gem",
    "createmyway:perfect_diamond_gem": "createmyway:gem",
    "createmyway:perfect_dulling_gem": "createmyway:gem",
    "createmyway:perfect_ember_gem": "createmyway:gem",
    "createmyway:perfect_emerald_gem": "createmyway:gem",
    "createmyway:perfect_frost_gem": "createmyway:gem",
    "createmyway:perfect_lapis_gem": "createmyway:gem",
    "createmyway:perfect_quartz_gem": "createmyway:gem",
    "createmyway:perfect_rose_quartz_gem": "createmyway:gem",
    "createmyway:perfect_venom_gem": "createmyway:gem",
    "createmyway:perfect_wither_gem": "createmyway:gem",
    "createmyway:refined_amethyst_gem": "createmyway:gem",
    "createmyway:refined_diamond_gem": "createmyway:gem",
    "createmyway:refined_dulling_gem": "createmyway:gem",
    "createmyway:refined_ember_gem": "createmyway:gem",
    "createmyway:refined_emerald_gem": "createmyway:gem",
    "createmyway:refined_frost_gem": "createmyway:gem",
    "createmyway:refined_lapis_gem": "createmyway:gem",
    "createmyway:refined_quartz_gem": "createmyway:gem",
    "createmyway:refined_rose_quartz_gem": "createmyway:gem",
    "createmyway:refined_venom_gem": "createmyway:gem",
    "createmyway:refined_wither_gem": "createmyway:gem",
    "createmyway:rose_gold_handle": "createmyway:handle",
    "createmyway:wooden_handle": "createmyway:handle"
  },
  "materialEquipment": {
    "createmyway:amethyst_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:copper_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_diamond_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_dulling_gem": [
      "sword"
    ],
    "createmyway:cut_ember_gem": [
      "sword"
    ],
    "createmyway:cut_emerald_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_frost_gem": [
      "sword"
    ],
    "createmyway:cut_lapis_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_rose_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:cut_venom_gem": [
      "sword"
    ],
    "createmyway:cut_wither_gem": [
      "sword"
    ],
    "createmyway:deep_alloy_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:diamond_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:echo_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:gold_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:iron_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:netherite_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:obsidian_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_amethyst_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_diamond_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_dulling_gem": [
      "sword"
    ],
    "createmyway:perfect_ember_gem": [
      "sword"
    ],
    "createmyway:perfect_emerald_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_frost_gem": [
      "sword"
    ],
    "createmyway:perfect_lapis_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_rose_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:perfect_venom_gem": [
      "sword"
    ],
    "createmyway:perfect_wither_gem": [
      "sword"
    ],
    "createmyway:refined_amethyst_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_diamond_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_dulling_gem": [
      "sword"
    ],
    "createmyway:refined_ember_gem": [
      "sword"
    ],
    "createmyway:refined_emerald_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_frost_gem": [
      "sword"
    ],
    "createmyway:refined_lapis_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_rose_quartz_gem": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:refined_venom_gem": [
      "sword"
    ],
    "createmyway:refined_wither_gem": [
      "sword"
    ],
    "createmyway:rose_gold_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ],
    "createmyway:wooden_handle": [
      "pickaxe",
      "axe",
      "shovel",
      "hoe",
      "sword"
    ]
  },
  "materialEffects": {
    "createmyway:amethyst_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:silk_touch": 1
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sweeping_edge": 1
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:silk_touch": 1
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:silk_touch": 1
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:silk_touch": 1
        }
      }
    },
    "createmyway:cut_diamond_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:unbreaking": 1
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:unbreaking": 1
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:unbreaking": 1
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:unbreaking": 1
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:unbreaking": 1
        }
      }
    },
    "createmyway:cut_dulling_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:weakness",
          "duration_ticks": 60,
          "amplifier": 0
        }
      }
    },
    "createmyway:cut_ember_gem": {
      "sword": {
        "fire_seconds": 3
      }
    },
    "createmyway:cut_emerald_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:fortune": 1
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:looting": 1
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:fortune": 1
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:fortune": 1
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:fortune": 1
        }
      }
    },
    "createmyway:cut_frost_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:slowness",
          "duration_ticks": 60,
          "amplifier": 0
        }
      }
    },
    "createmyway:cut_quartz_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:efficiency": 2
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sharpness": 1
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:efficiency": 2
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:efficiency": 2
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:efficiency": 2
        }
      }
    },
    "createmyway:cut_rose_quartz_gem": {
      "pickaxe": {
        "block_reach": 0.5
      },
      "sword": {
        "attack_reach": 0.25
      },
      "shovel": {
        "block_reach": 0.5
      },
      "hoe": {
        "block_reach": 0.5
      },
      "axe": {
        "block_reach": 0.5
      }
    },
    "createmyway:cut_venom_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:poison",
          "duration_ticks": 60,
          "amplifier": 0
        }
      }
    },
    "createmyway:cut_wither_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:wither",
          "duration_ticks": 60,
          "amplifier": 0
        }
      }
    },
    "createmyway:echo_gem": {
      "pickaxe": {
        "collect_drops": true
      },
      "sword": {
        "collect_drops": true
      },
      "shovel": {
        "collect_drops": true
      },
      "hoe": {
        "collect_drops": true
      },
      "axe": {
        "collect_drops": true
      }
    },
    "createmyway:perfect_amethyst_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 4
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sweeping_edge": 3
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 4
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 4
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 4
        }
      }
    },
    "createmyway:perfect_diamond_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:unbreaking": 3
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:unbreaking": 3
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:unbreaking": 3
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:unbreaking": 3
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:unbreaking": 3
        }
      }
    },
    "createmyway:perfect_dulling_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:weakness",
          "duration_ticks": 140,
          "amplifier": 2
        }
      }
    },
    "createmyway:perfect_ember_gem": {
      "sword": {
        "fire_seconds": 7
      }
    },
    "createmyway:perfect_emerald_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:fortune": 3
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:looting": 3
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:fortune": 3
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:fortune": 3
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:fortune": 3
        }
      }
    },
    "createmyway:perfect_frost_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:slowness",
          "duration_ticks": 140,
          "amplifier": 2
        }
      }
    },
    "createmyway:perfect_quartz_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:efficiency": 5
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sharpness": 5
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:efficiency": 5
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:efficiency": 5
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:efficiency": 5
        }
      }
    },
    "createmyway:perfect_rose_quartz_gem": {
      "pickaxe": {
        "block_reach": 1.5
      },
      "sword": {
        "attack_reach": 0.75
      },
      "shovel": {
        "block_reach": 1.5
      },
      "hoe": {
        "block_reach": 1.5
      },
      "axe": {
        "block_reach": 1.5
      }
    },
    "createmyway:perfect_venom_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:poison",
          "duration_ticks": 140,
          "amplifier": 2
        }
      }
    },
    "createmyway:perfect_wither_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:wither",
          "duration_ticks": 140,
          "amplifier": 2
        }
      }
    },
    "createmyway:refined_amethyst_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 2
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sweeping_edge": 2
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 2
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 2
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:silk_touch": 1,
          "minecraft:efficiency": 2
        }
      }
    },
    "createmyway:refined_diamond_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:unbreaking": 2
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:unbreaking": 2
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:unbreaking": 2
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:unbreaking": 2
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:unbreaking": 2
        }
      }
    },
    "createmyway:refined_dulling_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:weakness",
          "duration_ticks": 100,
          "amplifier": 1
        }
      }
    },
    "createmyway:refined_ember_gem": {
      "sword": {
        "fire_seconds": 5
      }
    },
    "createmyway:refined_emerald_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:fortune": 2
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:looting": 2
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:fortune": 2
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:fortune": 2
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:fortune": 2
        }
      }
    },
    "createmyway:refined_frost_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:slowness",
          "duration_ticks": 100,
          "amplifier": 1
        }
      }
    },
    "createmyway:refined_quartz_gem": {
      "pickaxe": {
        "enchantments": {
          "minecraft:efficiency": 4
        }
      },
      "sword": {
        "enchantments": {
          "minecraft:sharpness": 3
        }
      },
      "shovel": {
        "enchantments": {
          "minecraft:efficiency": 4
        }
      },
      "hoe": {
        "enchantments": {
          "minecraft:efficiency": 4
        }
      },
      "axe": {
        "enchantments": {
          "minecraft:efficiency": 4
        }
      }
    },
    "createmyway:refined_rose_quartz_gem": {
      "pickaxe": {
        "block_reach": 1.0
      },
      "sword": {
        "attack_reach": 0.5
      },
      "shovel": {
        "block_reach": 1.0
      },
      "hoe": {
        "block_reach": 1.0
      },
      "axe": {
        "block_reach": 1.0
      }
    },
    "createmyway:refined_venom_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:poison",
          "duration_ticks": 100,
          "amplifier": 1
        }
      }
    },
    "createmyway:refined_wither_gem": {
      "sword": {
        "status_effect": {
          "id": "minecraft:wither",
          "duration_ticks": 100,
          "amplifier": 1
        }
      }
    }
  },
  "materialTiers": {
    "createmyway:amethyst_gem": "cut",
    "createmyway:copper_handle": "single",
    "createmyway:cut_diamond_gem": "cut",
    "createmyway:cut_dulling_gem": "cut",
    "createmyway:cut_ember_gem": "cut",
    "createmyway:cut_emerald_gem": "cut",
    "createmyway:cut_frost_gem": "cut",
    "createmyway:cut_lapis_gem": "cut",
    "createmyway:cut_quartz_gem": "cut",
    "createmyway:cut_rose_quartz_gem": "cut",
    "createmyway:cut_venom_gem": "cut",
    "createmyway:cut_wither_gem": "cut",
    "createmyway:deep_alloy_handle": "single",
    "createmyway:diamond_handle": "single",
    "createmyway:echo_gem": "single",
    "createmyway:gold_handle": "single",
    "createmyway:iron_handle": "single",
    "createmyway:netherite_handle": "single",
    "createmyway:obsidian_handle": "single",
    "createmyway:perfect_amethyst_gem": "perfect",
    "createmyway:perfect_diamond_gem": "perfect",
    "createmyway:perfect_dulling_gem": "perfect",
    "createmyway:perfect_ember_gem": "perfect",
    "createmyway:perfect_emerald_gem": "perfect",
    "createmyway:perfect_frost_gem": "perfect",
    "createmyway:perfect_lapis_gem": "perfect",
    "createmyway:perfect_quartz_gem": "perfect",
    "createmyway:perfect_rose_quartz_gem": "perfect",
    "createmyway:perfect_venom_gem": "perfect",
    "createmyway:perfect_wither_gem": "perfect",
    "createmyway:refined_amethyst_gem": "refined",
    "createmyway:refined_diamond_gem": "refined",
    "createmyway:refined_dulling_gem": "refined",
    "createmyway:refined_ember_gem": "refined",
    "createmyway:refined_emerald_gem": "refined",
    "createmyway:refined_frost_gem": "refined",
    "createmyway:refined_lapis_gem": "refined",
    "createmyway:refined_quartz_gem": "refined",
    "createmyway:refined_rose_quartz_gem": "refined",
    "createmyway:refined_venom_gem": "refined",
    "createmyway:refined_wither_gem": "refined",
    "createmyway:rose_gold_handle": "single",
    "createmyway:wooden_handle": "single"
  },
  "materialNames": {
    "createmyway:amethyst_gem": "Cut Amethyst Gem",
    "createmyway:copper_handle": "Copper Handle",
    "createmyway:cut_diamond_gem": "Cut Diamond Gem",
    "createmyway:cut_dulling_gem": "Cut Dulling Gem",
    "createmyway:cut_ember_gem": "Cut Ember Gem",
    "createmyway:cut_emerald_gem": "Cut Emerald Gem",
    "createmyway:cut_frost_gem": "Cut Frost Gem",
    "createmyway:cut_lapis_gem": "Cut Lapis Gem",
    "createmyway:cut_quartz_gem": "Cut Quartz Gem",
    "createmyway:cut_rose_quartz_gem": "Cut Rose Quartz Gem",
    "createmyway:cut_venom_gem": "Cut Venom Gem",
    "createmyway:cut_wither_gem": "Cut Wither Gem",
    "createmyway:deep_alloy_handle": "Deep Alloy Handle",
    "createmyway:diamond_handle": "Diamond Handle",
    "createmyway:echo_gem": "Echo Gem",
    "createmyway:gold_handle": "Gold Handle",
    "createmyway:iron_handle": "Iron Handle",
    "createmyway:netherite_handle": "Netherite Handle",
    "createmyway:obsidian_handle": "Obsidian Handle",
    "createmyway:perfect_amethyst_gem": "Perfect Amethyst Gem",
    "createmyway:perfect_diamond_gem": "Perfect Diamond Gem",
    "createmyway:perfect_dulling_gem": "Perfect Dulling Gem",
    "createmyway:perfect_ember_gem": "Perfect Ember Gem",
    "createmyway:perfect_emerald_gem": "Perfect Emerald Gem",
    "createmyway:perfect_frost_gem": "Perfect Frost Gem",
    "createmyway:perfect_lapis_gem": "Perfect Lapis Gem",
    "createmyway:perfect_quartz_gem": "Perfect Quartz Gem",
    "createmyway:perfect_rose_quartz_gem": "Perfect Rose Quartz Gem",
    "createmyway:perfect_venom_gem": "Perfect Venom Gem",
    "createmyway:perfect_wither_gem": "Perfect Wither Gem",
    "createmyway:refined_amethyst_gem": "Refined Amethyst Gem",
    "createmyway:refined_diamond_gem": "Refined Diamond Gem",
    "createmyway:refined_dulling_gem": "Refined Dulling Gem",
    "createmyway:refined_ember_gem": "Refined Ember Gem",
    "createmyway:refined_emerald_gem": "Refined Emerald Gem",
    "createmyway:refined_frost_gem": "Refined Frost Gem",
    "createmyway:refined_lapis_gem": "Refined Lapis Gem",
    "createmyway:refined_quartz_gem": "Refined Quartz Gem",
    "createmyway:refined_rose_quartz_gem": "Refined Rose Quartz Gem",
    "createmyway:refined_venom_gem": "Refined Venom Gem",
    "createmyway:refined_wither_gem": "Refined Wither Gem",
    "createmyway:rose_gold_handle": "Rose Gold Handle",
    "createmyway:wooden_handle": "Wooden Handle"
  },
  "materialDescriptions": {
    "createmyway:amethyst_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:copper_handle": "An accessible early handle with balanced speed and durability.",
    "createmyway:cut_diamond_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_dulling_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_ember_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_emerald_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_frost_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_lapis_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_rose_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_venom_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:cut_wither_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:deep_alloy_handle": "A heavy, fireproof handle focused on dependable durability.",
    "createmyway:diamond_handle": "A balanced high-tier handle with strong speed and durability.",
    "createmyway:echo_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:gold_handle": "Exceptionally fast and enchantable, but extremely fragile.",
    "createmyway:iron_handle": "A dependable baseline handle that favors durability over speed.",
    "createmyway:netherite_handle": "An endgame fireproof handle with exceptional durability.",
    "createmyway:obsidian_handle": "Extremely durable and deliberately slow for heavy-duty tools.",
    "createmyway:perfect_amethyst_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_diamond_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_dulling_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_ember_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_emerald_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_frost_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_lapis_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_rose_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_venom_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:perfect_wither_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_amethyst_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_diamond_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_dulling_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_ember_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_emerald_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_frost_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_lapis_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_rose_quartz_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_venom_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:refined_wither_gem": "Adds a special ability and tunes the finished tool's stats.",
    "createmyway:rose_gold_handle": "A responsive, high-speed handle that trades away durability.",
    "createmyway:wooden_handle": "A light, inexpensive starter handle with quick handling but low durability."
  },
  "materialStats": {
    "createmyway:amethyst_gem": {
      "role": "gem",
      "durability": 44.8,
      "miningSpeed": 2.1,
      "attackPower": 5.5,
      "enchantability": 54,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:copper_handle": {
      "role": "handle",
      "durability": 288.0,
      "miningSpeed": 10.0,
      "attackPower": 4.5,
      "enchantability": 10.0,
      "miningTier": 0.0,
      "defense": 4.0,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_diamond_gem": {
      "role": "gem",
      "durability": 204.8,
      "miningSpeed": 2.4,
      "attackPower": 6,
      "enchantability": 30,
      "miningTier": 0.0,
      "defense": 8,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_dulling_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_ember_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_emerald_gem": {
      "role": "gem",
      "durability": 102.4,
      "miningSpeed": 2.4,
      "attackPower": 5.5,
      "enchantability": 27,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_frost_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_lapis_gem": {
      "role": "gem",
      "durability": 76.8,
      "miningSpeed": 0.9,
      "attackPower": 4.5,
      "enchantability": 25,
      "miningTier": 0.0,
      "defense": 3,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_quartz_gem": {
      "role": "gem",
      "durability": 57.6,
      "miningSpeed": 2.1,
      "attackPower": 6.5,
      "enchantability": 48,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_rose_quartz_gem": {
      "role": "gem",
      "durability": 96,
      "miningSpeed": 2.7,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_venom_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:cut_wither_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:deep_alloy_handle": {
      "role": "handle",
      "durability": 960.0,
      "miningSpeed": 9.5,
      "attackPower": 5.0,
      "enchantability": 11.0,
      "miningTier": 0.0,
      "defense": 7.0,
      "toughness": 0,
      "knockbackResistance": 0.1,
      "fireproof": true
    },
    "createmyway:diamond_handle": {
      "role": "handle",
      "durability": 768,
      "miningSpeed": 14.5,
      "attackPower": 6,
      "enchantability": 12,
      "miningTier": 0.0,
      "defense": 8,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:echo_gem": {
      "role": "gem",
      "durability": 307.2,
      "miningSpeed": 3,
      "attackPower": 7,
      "enchantability": 72,
      "miningTier": 0.0,
      "defense": 9,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:gold_handle": {
      "role": "handle",
      "durability": 128.0,
      "miningSpeed": 20.0,
      "attackPower": 3.0,
      "enchantability": 24.0,
      "miningTier": 0.0,
      "defense": 3.0,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:iron_handle": {
      "role": "handle",
      "durability": 512,
      "miningSpeed": 12,
      "attackPower": 5,
      "enchantability": 12,
      "miningTier": 0.0,
      "defense": 6,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:netherite_handle": {
      "role": "handle",
      "durability": 1536.0,
      "miningSpeed": 11.0,
      "attackPower": 7.0,
      "enchantability": 15.0,
      "miningTier": 0.0,
      "defense": 9.0,
      "toughness": 0,
      "knockbackResistance": 0.1,
      "fireproof": true
    },
    "createmyway:obsidian_handle": {
      "role": "handle",
      "durability": 1280,
      "miningSpeed": 8,
      "attackPower": 6.5,
      "enchantability": 18,
      "miningTier": 0.0,
      "defense": 10,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_amethyst_gem": {
      "role": "gem",
      "durability": 44.8,
      "miningSpeed": 2.1,
      "attackPower": 5.5,
      "enchantability": 54,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_diamond_gem": {
      "role": "gem",
      "durability": 204.8,
      "miningSpeed": 2.4,
      "attackPower": 6,
      "enchantability": 30,
      "miningTier": 0.0,
      "defense": 8,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_dulling_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_ember_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_emerald_gem": {
      "role": "gem",
      "durability": 102.4,
      "miningSpeed": 2.4,
      "attackPower": 5.5,
      "enchantability": 27,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_frost_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_lapis_gem": {
      "role": "gem",
      "durability": 76.8,
      "miningSpeed": 0.9,
      "attackPower": 4.5,
      "enchantability": 75,
      "miningTier": 0.0,
      "defense": 3,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_quartz_gem": {
      "role": "gem",
      "durability": 57.6,
      "miningSpeed": 2.1,
      "attackPower": 6.5,
      "enchantability": 48,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_rose_quartz_gem": {
      "role": "gem",
      "durability": 96,
      "miningSpeed": 2.7,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_venom_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:perfect_wither_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_amethyst_gem": {
      "role": "gem",
      "durability": 44.8,
      "miningSpeed": 2.1,
      "attackPower": 5.5,
      "enchantability": 54,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_diamond_gem": {
      "role": "gem",
      "durability": 204.8,
      "miningSpeed": 2.4,
      "attackPower": 6,
      "enchantability": 30,
      "miningTier": 0.0,
      "defense": 8,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_dulling_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_ember_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_emerald_gem": {
      "role": "gem",
      "durability": 102.4,
      "miningSpeed": 2.4,
      "attackPower": 5.5,
      "enchantability": 27,
      "miningTier": 0.0,
      "defense": 5,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_frost_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_lapis_gem": {
      "role": "gem",
      "durability": 76.8,
      "miningSpeed": 0.9,
      "attackPower": 4.5,
      "enchantability": 50,
      "miningTier": 0.0,
      "defense": 3,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_quartz_gem": {
      "role": "gem",
      "durability": 57.6,
      "miningSpeed": 2.1,
      "attackPower": 6.5,
      "enchantability": 48,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_rose_quartz_gem": {
      "role": "gem",
      "durability": 96,
      "miningSpeed": 2.7,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_venom_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:refined_wither_gem": {
      "role": "gem",
      "durability": 80,
      "miningSpeed": 1.8,
      "attackPower": 5.5,
      "enchantability": 24,
      "miningTier": 0.0,
      "defense": 4,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:rose_gold_handle": {
      "role": "handle",
      "durability": 384,
      "miningSpeed": 17,
      "attackPower": 6,
      "enchantability": 15,
      "miningTier": 0.0,
      "defense": 6,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    },
    "createmyway:wooden_handle": {
      "role": "handle",
      "durability": 96.0,
      "miningSpeed": 13.0,
      "attackPower": 2.0,
      "enchantability": 8.0,
      "miningTier": 0.0,
      "defense": 2.0,
      "toughness": 0,
      "knockbackResistance": 0,
      "fireproof": false
    }
  },
  "partStats": {
    "handle": {
      "id": "createmyway:handle",
      "segment_part": "createmyway:parts/handles",
      "sort_order": 20,
      "durability_modifier": 0.5,
      "tier_modifier": 4.0,
      "enchantability_modifier": 0.4
    },
    "gem": {
      "id": "createmyway:gem",
      "segment_part": "createmyway:parts/gems",
      "sort_order": 19,
      "durability_modifier": 0.5,
      "tier_modifier": 4.0,
      "enchantability_modifier": 0.4
    }
  },
  "customPartIds": [
    "createmyway:gem",
    "createmyway:handle"
  ]
}
