// AUTO-GENERATED BY create_my_way_material_generator.py
// Do not edit this file manually.

ServerEvents.recipes(event => {

  event.recipes.createmetallurgy.casting_in_table(
    Item.of("slag:dynamic_part[slag:material_type=\"createmyway:iron_handle\",slag:part_type=\"createmyway:handle\"]"),
    [
      Fluid.of("createmetallurgy:molten_iron", 45),
      "createmetallurgy:graphite_rod_mold"
    ]
  ).processingTime(30).id("createmyway:form_iron_handle")

  event.recipes.createmetallurgy.casting_in_table(
    Item.of("slag:dynamic_part[slag:material_type=\"createmyway:rose_gold_handle\",slag:part_type=\"createmyway:handle\"]"),
    [
      Fluid.of("slag:molten_rose_gold", 45),
      "createmetallurgy:graphite_rod_mold"
    ]
  ).processingTime(30).id("createmyway:form_rose_gold_handle")

})
